# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robot.ui'
#
# Created: Fri Jun 29 11:30:27 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(963, 598)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.groupBox_5 = QtGui.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(30, 0, 901, 491))
        self.groupBox_5.setStyleSheet("font: 75 14pt \"Corbel\";")
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox.setGeometry(QtCore.QRect(30, 50, 391, 131))
        self.groupBox.setStyleSheet("font: 75 9pt \"微软雅黑\";")
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(40, 50, 61, 16))
        self.label.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(110, 50, 151, 20))
        self.lineEdit.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(280, 50, 75, 23))
        self.pushButton.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_7.setGeometry(QtCore.QRect(110, 90, 151, 20))
        self.lineEdit_7.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(20, 90, 81, 16))
        self.label_8.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.label_8.setObjectName("label_8")
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 200, 391, 81))
        self.groupBox_4.setStyleSheet("font: 75 9pt \"微软雅黑\";")
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(20, 40, 71, 16))
        self.label_4.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.label_4.setObjectName("label_4")
        self.comboBox = QtGui.QComboBox(self.groupBox_4)
        self.comboBox.setGeometry(QtCore.QRect(110, 40, 151, 22))
        self.comboBox.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 310, 391, 151))
        self.groupBox_3.setStyleSheet("font: 75 9pt \"微软雅黑\";")
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 101, 16))
        self.label_3.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setGeometry(QtCore.QRect(110, 80, 151, 20))
        self.lineEdit_3.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_3 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 80, 75, 23))
        self.pushButton_3.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.radioButton = QtGui.QRadioButton(self.groupBox_3)
        self.radioButton.setEnabled(True)
        self.radioButton.setGeometry(QtCore.QRect(20, 40, 161, 16))
        self.radioButton.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.radioButton.setObjectName("radioButton")
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(40, 120, 71, 16))
        self.label_7.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setGeometry(QtCore.QRect(110, 120, 151, 20))
        self.lineEdit_6.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_2.setGeometry(QtCore.QRect(490, 50, 381, 131))
        self.groupBox_2.setStyleSheet("font: 75 9pt \"微软雅黑\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(40, 50, 131, 16))
        self.label_5.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 50, 161, 20))
        self.lineEdit_4.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(180, 90, 161, 20))
        self.lineEdit_5.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(60, 90, 111, 16))
        self.label_6.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.label_6.setObjectName("label_6")
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(490, 200, 381, 171))
        self.groupBox_6.setStyleSheet("font: 75 9pt \"微软雅黑\";")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_10 = QtGui.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(90, 50, 71, 16))
        self.label_10.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.label_10.setObjectName("label_10")
        self.lineEdit_9 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_9.setGeometry(QtCore.QRect(180, 50, 161, 20))
        self.lineEdit_9.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_10.setGeometry(QtCore.QRect(180, 90, 161, 20))
        self.lineEdit_10.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(90, 90, 71, 16))
        self.label_11.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.label_11.setObjectName("label_11")
        self.lineEdit_13 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_13.setGeometry(QtCore.QRect(180, 130, 161, 20))
        self.lineEdit_13.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.label_14 = QtGui.QLabel(self.groupBox_6)
        self.label_14.setGeometry(QtCore.QRect(90, 130, 71, 16))
        self.label_14.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.label_14.setObjectName("label_14")
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_7.setGeometry(QtCore.QRect(490, 390, 381, 71))
        self.groupBox_7.setStyleSheet("font: 75 9pt \"微软雅黑\";")
        self.groupBox_7.setObjectName("groupBox_7")
        self.lineEdit_16 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_16.setGeometry(QtCore.QRect(180, 130, 161, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_17 = QtGui.QLabel(self.groupBox_7)
        self.label_17.setGeometry(QtCore.QRect(40, 130, 111, 16))
        self.label_17.setObjectName("label_17")
        self.progressBar = QtGui.QProgressBar(self.groupBox_7)
        self.progressBar.setGeometry(QtCore.QRect(40, 30, 341, 23))
        self.progressBar.setStyleSheet("font: 8pt \"Times New Roman\";")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.line = QtGui.QFrame(self.groupBox_5)
        self.line.setGeometry(QtCore.QRect(450, 50, 20, 411))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_5 = QtGui.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(330, 530, 301, 41))
        self.pushButton_5.setCursor(QtCore.Qt.ArrowCursor)
        self.pushButton_5.setStyleSheet("font: 75 8pt \"Comic Sans MS\";\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Form", "Experiment Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "State Path Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "State Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Form", "Select Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Check Interval:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Form", "Position Matrix Type Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Matrix Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Form", "    8 × 8", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Form", "  16 × 16", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("Form", "  32 × 32", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("Form", "  64 × 64", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("Form", "128 × 128", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(5, QtGui.QApplication.translate("Form", "256 × 256", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(6, QtGui.QApplication.translate("Form", "512 × 512", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Setpoint Matrix Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Matrix File Path:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Form", "Select File", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton.setText(QtGui.QApplication.translate("Form", "Enable Setpoint Matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Sheet Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Settling Time Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Approach Settling Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Move Settling Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Form", "Trigger Signal Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Form", "High Voltage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Low Voltage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Holding Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Form", "Progress", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Holding Time", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p>Please be patient</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setToolTip(QtGui.QApplication.translate("Form", "<html><head/><body><p><span style=\" font-size:8pt; font-weight:400;\">Click me</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("Form", "Start Experiment", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

